### ISSUE TITLE
Searching for a Joomla Developer

### ISSUE THREAD

**Issue by demis-palma** [Fedik/mooOptionTree#1]
Content removed to protect your privacy.
Please contact us by email: demis (at) fox.ra.it if interested.

Demis Palma
Fox Labs

**Comment by Fedik** [comment]
Hi,

Thanks for suggestion, 
for now I am not available, but thanks for suggestion, I will keep it in mind :wink:

**Comment by demis-palma** [comment]
Don't hesitate contacting me anytime if you change your mind.
Have a nice day!
